# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b124e12460b5a8e0653995e12a7ed40685e6fa6e46deed531b0c16502a0f4eed65bc1d1474dfbf9dcae684a7b67dfb9137b9ad99c8a9113f387d0285673cdf

test:
  secret_key_base: fcf38f1a5a4ae23cde4f9dd1394ea5360ea57fbd5905d3160a48beba2bcaf722f457d8388009aab6d345f77679b00511ad806363058ad05d765c22d75ba98b99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
